services:
  web:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/app
    depends_on:
      - php7-fpm

  php7-fpm:
    build:
      context: docker
      dockerfile: php/7.4/Dockerfile
    volumes:
      - ./:/app
      - ./docker/common/php:/usr/local/etc/php/conf.d
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'db:/var/lib/mysql'

networks:
  tradecar:
    driver: bridge

volumes:
  db:
    driver: local